### PR TITLE
voidkill changes

### PR DESCRIPTION
**Pull request by ImYenil**
Changed void kill code in version 1.19.4

### CODE REVIEW

**Comment by tomkeuper** [comment]
Can you explain why you changed it?

**Comment by ImYenil** [comment]
> Can you explain why you changed it?

Until version 1.19.3 void kill used nms. But even in version 1.19.4 it's because they implemented void kill in nms

**Comment by tomkeuper** [comment]
> > Can you explain why you changed it?
> 
> Until version 1.19.3 void kill used nms. But even in version 1.19.4 it's because they implemented void kill in nms

I dont understand what you are trying to say

**Comment by tomkeuper** [comment]
And if you are saying that there is no void kill in 1.19.4. Like I said before its renamed to DamageTypes.Out_of-world

**Comment by ImYenil** [comment]
> And if you are saying that there is no void kill in 1.19.4. Like I said before its renamed to DamageTypes.Out_of-world

image
image
image

**Review by porudev — COMMENTED** [review]
Can you explain what those function do, i understand it void kill but what is dg() and other stuff

**Pull request closed without merging**
