### PR TITLE
Added more placeholders.

### PR DESCRIPTION
**Pull request by AgentNoobff**
Added more placeholders to BedWars2023 itself so that an external PlaceholderAPI expansion isn't required.

Added Placeholders:
%bw2023_team_letter%
%bw2023_team_color%
%bw2023_team_status%
%bw2023_team_players_amount%
%bw2023_team_players%
%bw2023_team_letter_<team>%
%bw2023_team_color_<team>%
%bw2023_team_status_<team>%
%bw2023_team_players_amount_<team>%
%bw2023_team_players_<team>%
%bw2023_arena_nextevent%
%bw2023_arena_nextevent_name%
%bw2023_arena_nextevent_time%
%bw2023_arena_name%
%bw2023_arena_group%
%bw2023_arena_world%
%bw2023_arena_status_plocale%
%bw2023_arena_status%
%bw2023_player_kills%
%bw2023_player_kills_final%
%bw2023_player_kills_total%
%bw2023_player_deaths%
%bw2023_player_deaths_final%
%bw2023_player_deaths_total%
%bw2023_player_beds%
%bw2023_players%
%bw2023_players_amount%
%bw2023_party_has%
%bw2023_party_members%
%bw2023_party_members_amount%
%bw2023_party_in_yours_<player>%
%bw2023_party_in_his_<player>%
%bw2023_party_is_owner%

### CODE REVIEW

**Review by tomkeuper — APPROVED** [review]

**Comment by tomkeuper** [comment]
Can you create some general examples for the placeholders that need some sort of extra data? This way they can be easily added to the documentation
https://dev-wiki.tomkeuper.com/docs/BedWars2023/hooks/papi-hook

**Comment by AgentNoobff** [comment]
> Can you create some general examples for the placeholders that need some sort of extra data? This way they can be easily added to the documentation
> https://dev-wiki.tomkeuper.com/docs/BedWars2023/hooks/papi-hook

You mean adding them to the wiki?

**Comment by AgentNoobff** [comment]
Ah ic now, I'll do it.

**Comment by AgentNoobff** [comment]
%bw2023_team_letter% - Returns the first letter of the display name of the team the player is in.
%bw2023_team_color% - Returns the colour of the team the player is in.
%bw2023_team_status% - Returns the status (✓, <number of players> or ×) of the team the player is in.
%bw2023_team_players_amount% - Returns the number of players in the team.
%bw2023_team_players% - Returns the players in the team, which the player is in, in the form of a String with names separated by ", ".
%bw2023_team_letter_<player>% - Returns the first letter of the display name of the teM the player specified is in.
%bw2023_team_color_<player>% - Returns the colour of the team the player specified is in.
%bw2023_team_status_<player>% - Returns the status (✓, <number of players> or ×) of the team the player specified is in.
%bw2023_team_players_amount_<player>% - Returns the number of players in the team the player specified is in.
%bw2023_team_players_<player>% - Returns the players in the team, which the player specified is in, in the form of a String with names separated by ", ".
%bw2023_arena_nextevent_name% - Returns the name of the next event of the arena the player is in.
%bw2023_arena_nextevent_time% - Returns the time left till the next event of the arena the player is in, in raw form as String.
%bw2023_arena_nextevent_time_formatted% - Returns the time left till the next event of the arena the player is in, in formatted form as String.
%bw2023_arena_name% - Returns the name of the arena the player is in.
%bw2023_arena_displayName% - Returns the display name of the arena the player is in.
%bw2023_arena_group% - Returns the group the arena, which the player is in, is in.
%bw2023_arena_world% - Returns the world the arena, which the player is in, is in.
%bw2023_arena_status_plocale% - Returns the status of the arena in the player's chosen language.
%bw2023_arena_status% - Returns the status of the arena in the default language.
%bw2023_player_kills% - Returns the number of kills the player has done in that particular game.
%bw2023_player_kills_final% - Returns the number of final kills the player has done in that particular game.
%bw2023_player_kills_total% - Returns the total number of kills (kills + final kills) the player has done in that particular game.
%bw2023_player_deaths% - Returns the number of times the player has died in that particular game.
%bw2023_player_deaths_final% - Returns the number of times the player has died the final time in that particular game. (Supposed to be always less than or equal to 1)
%bw2023_player_deaths_total% - Returns the total number of times the player has died (deaths + final deaths) in that particular game.
%bw2023_player_beds% - Returns the number of beds the player has broken in that particular game.
%bw2023_players% - Returns the players in the arena, which the player is in, in the form of a String with names separated by ", ".
%bw2023_players_amount% - Returns the number of players in the arena the player is in.
%bw2023_party_has% - Returns "true" if the player is in a party and "false" if the player is not.
%bw2023_party_members% - Returns the members of the party, which the player is in, in the form of a String with names separated by ", ".
%bw2023_party_members_amount% - Returns the number of members of the party the player is in.
%bw2023_party_in_yours_<target>% - Returns "true" if the target specified is in the player's party and "false" if not.
%bw2023_party_in_his_<target>% - Returns "true" if the player is in the target's party and "false" if not.
%bw2023_party_is_owner% - Returns "true" if the player is the owner of his party and "false" if not.

Here you go :)! There are some changes to the number and names of the placeholders in the list so I'd recommend following this and not the previous.

**Pull request merged**
