### PR TITLE
Fix cannot measure distance between A and B

### PR DESCRIPTION
**Pull request by ImYenil**
Fix cannot measure distance between A and B

### CODE REVIEW

**Review by porudev — COMMENTED** [review]
can you explain what this do? like on what use case

**Comment by ImYenil** [comment]
> can you explain what this do? like on what use case

https://github.com/tomkeuper/BedWars1058/pull/74

**Comment by tomkeuper** [comment]
My questions stays; why did you use continue for 1 and return for the other?
What does it do in the function

**Comment by ImYenil** [comment]
> My questions stays; why did you use continue for 1 and return for the other? What does it do in the function

Will change

**Comment by ImYenil** [comment]
Changed

**Review by tomkeuper — APPROVED** [review]

**Pull request merged**
