### PR TITLE
fix Can buy item when no inventory space

### LINKED ISSUE #53: Can buy item when no inventory space
**Describe the bug**
When your inventory is full you can buy items from the shop, this will take the cost out of your inventory but it will not give you the item.

**To Reproduce**
Inv full > buy item from shop

### PR DESCRIPTION
**Pull request by ImYenil**
Fixed a bug where players could purchase items from the shop when their inventory was full

### CODE REVIEW

**Comment by tomkeuper** [comment]
Is it not better to resolve this in the CategoryContent class?  Becausethats there the event gets called and its better to handle stuff like that directly.

**Comment by ImYenil** [comment]
> CategoryContent

I tried it on the CategoryContent class. but, using this code in this class has a bug where items can be purchased even when the inventory is full, so it has been replaced with ShopBuyEvent.

**Comment by tomkeuper** [comment]
> > CategoryContent
> 
> I tried it on the CategoryContent class. but, using this code in this class has a bug where items can be purchased even when the inventory is full, so it has been replaced with ShopBuyEvent.

All the variables you need are passed thru the event and are already present in the CategoryContent class. All you basically need to do is check the inventory there and if its full return out of the function.

**Comment by ImYenil** [comment]
> All the variables you need are passed thru the event and are already present in the CategoryContent class. All you basically need to do is check the inventory there and if its full return out of the function.

Do I really have to do that? Shouldn't it be enough to fix it?

**Comment by tomkeuper** [comment]
> > All the variables you need are passed thru the event and are already present in the CategoryContent class. All you basically need to do is check the inventory there and if its full return out of the function.
> 
> Do I really have to do that? Shouldn't it be enough to fix it?

Having to register an event listener is not a clean solution, all you basically have to do is copy paste the code you already have to the CategoryContant class.

**Comment by ImYenil** [comment]
> CategoryContant

Tried with the CategoryContant class, but this bug was not fixed.

**Comment by tomkeuper** [comment]
> > CategoryContant
> 
> Tried with the CategoryContant class, but this bug was not fixed.

I'll give it a look in a min

**Comment by ImYenil** [comment]
> > > CategoryContant
> > 
> > 
> > Tried with the CategoryContant class, but this bug was not fixed.
> 
> I'll give it a look in a min

ok

**Comment by tomkeuper** [comment]
closing in favor of 6e76033bed977f1251a666e3aa56890fc1797f72

**Pull request closed without merging**
