### PR TITLE
spectators-changes

### PR DESCRIPTION
**Pull request by ImYenil**
Spectators are now spawned with the SURVIVAL gamemode 
Grants an invisibility effect when the player dies (Request: https://github.com/andrei1058/BedWars1058/issues/748)

### CODE REVIEW

**Comment by tomkeuper** [comment]
Can you make sure spectators cannot block bow shots and other entities?

**Comment by ImYenil** [comment]
> Can you make sure spectators cannot block bow shots and other entities?

It already implemented

**Review by porudev — APPROVED** [review]
Looks good!

**Comment by tomkeuper** [comment]
Why survival btw? adventure gamemode is basically survival but prevents certain actions

**Comment by tomkeuper** [comment]
spectators are already invisible when they join an arena. the only thing I agree with is removing the particles

**Comment by tomkeuper** [comment]
Closing as Adventure mode is preffered and no further updates were provided

**Pull request closed without merging**
