### PR TITLE
Default Next Event Bed Destruction language fix

### PR DESCRIPTION
**Pull request by AgentNoobff**

### CODE REVIEW

**Comment by AgentNoobff** [comment]
Fixed all messages excluding Russian and Chinese because I have no idea what to do with them. We'll have to leave those languages up to the user :P

**Review by tomkeuper — APPROVED** [review]

**Comment by porudev** [comment]
I have updated it to a  more short and meaning full as follow of big server

**Review by porudev — APPROVED** [review]

**Comment by AgentNoobff** [comment]
Close this?

**Review by Xxyuri2005xX — APPROVED** [review]

**Comment by tomkeuper** [comment]
Could you open a new PR with these changes on the development branch?
It was set to Master and this one is too outdated

**Comment by tomkeuper** [comment]
Closing as implemented in commit b730cf4764af112bebf38e80274deb000e8254a0

**Pull request closed without merging**
