### PR TITLE
Implement PlayerStatChangeEvent

### PR DESCRIPTION
**Pull request by Xxyuri2005xX**

### CODE REVIEW

**Comment by KKiiya** [comment]
Wouldnt be better to add stat type with a enum in the event? So when someone wants to cancel a stat, the user can cancel a specific stat

**Comment by Xxyuri2005xX** [comment]
I can work on it, although implementing it will prove more difficult if even then tom were to implement methods in the stats to be able to create via API their own stats

**Comment by tomkeuper** [comment]
I kinda agree with KKiiya, just create an enum that has the different stats and then one named CUSTOM for the custom stats

**Comment by tomkeuper** [comment]
The rest looks good btw

**Comment by Xxyuri2005xX** [comment]
> I kinda agree with KKiiya, just create an enum that has the different stats and then one named CUSTOM for the custom stats

so an enum containing all the stats currently supported by BedWars and a CUSTOM one? i can do it

**Comment by Xxyuri2005xX** [comment]
I have implemented the statType, if any event is missing to be called or created let me know I will fix it

**Comment by tomkeuper** [comment]
Btw commit: 6dfa9cfe8b2c8da8b020f5f504cc379ca26d3019 is unrelated to this PR but since its a small addition its fine for now

**Review by tomkeuper — APPROVED** [review]

**Review by KKiiya — COMMENTED** [review]
You havent added the getStatType method to get the type of stat

**Comment by Xxyuri2005xX** [comment]
> You havent added the getStatType method to get the type of stat
> 

I can add that method, when i turn on the PC i work on that

**Comment by tomkeuper** [comment]
After thats implemented feel free to merge

**Comment by Xxyuri2005xX** [comment]
Implemented the getStatType with its javadoc

**Review by KKiiya — APPROVED** [review]

**Pull request merged**
