### PR TITLE
rejoin message twice

### PR DESCRIPTION
**Pull request by ImYenil**
Fixed bug where rejoin allowed message was sent twice

### CODE REVIEW

**Review by porudev — COMMENTED** [review]
If you delete it where is the other one, im just asking this

**Comment by ImYenil** [comment]
> If you delete it where is the other one, im just asking this

https://github.com/tomkeuper/BedWars1058/blob/master/bedwars-plugin/src/main/java/com/andrei1058/bedwars/commands/rejoin/RejoinCommand.java

image

**Review by porudev — APPROVED** [review]

**Comment by tomkeuper** [comment]
Does this have an effect on Bungee Mode?

**Comment by porudev** [comment]
> Does this have an effect on Bungee Mode?

as fair as i've seen no

**Review by tomkeuper — APPROVED** [review]

**Pull request merged**
