### PR TITLE
Update MenuTrapSlot.java

### PR DESCRIPTION
**Pull request by ImYenil**
Removed unnecessary lore from trap slot item

### CODE REVIEW

**Comment by tomkeuper** [comment]
This is not unnecessary, its used to differentiate between different imports, to make it easier to see what imports are used. Its even automatically added by ide's.

**Comment by tomkeuper** [comment]
Aahh i see what you mean now.
But what does this change in game?

**Comment by ImYenil** [comment]
> Aahh i see what you mean now. But what does this change in game?

Just a code update. There are two "" lines, so I removed one.

**Review by tomkeuper — APPROVED** [review]

**Comment by tomkeuper** [comment]
Gggrrrrrr masterr

**Pull request merged**
