### PR TITLE
fix eggbridge building above max build height

### PR DESCRIPTION
**Pull request by ImYenil**
Fix eggbridge go above build limit

### CODE REVIEW

**Comment by tomkeuper** [comment]
Could you also implement this for the pop up tower? because then it fully solves #61

**Comment by ImYenil** [comment]
> pop up tower

Does working on a bridge egg issue in a pop up tower branch mean that it needs to be moved?

**Comment by ImYenil** [comment]
> Could you also implement this for the pop up tower? because then it fully solves #61

Does that mean I have to move the bridge egg issue to the pop up tower branch?

**Comment by tomkeuper** [comment]
> > Could you also implement this for the pop up tower? because then it fully solves #61
> 
> Does that mean I have to move the bridge egg issue to the pop up tower branch?

Not for me, I was asking because both have the same issue and will have the same way to solve it.
And becuase the birdge egg was also mentioned in that issue, I thought it would be good to have both solved at the same time.

**Comment by tomkeuper** [comment]
But if you want to make a second PR about it thats fine too, just let me know!

**Comment by ImYenil** [comment]
> But if you want to make a second PR about it thats fine too, just let me know!

Yes i want

**Review by tomkeuper — APPROVED** [review]

**Review by porudev — APPROVED** [review]

**Pull request merged**
