### PR TITLE
Added generator split

### PR DESCRIPTION
**Pull request by tomkeuper**

### CODE REVIEW

**Comment by porudev** [comment]
Amongus Done yet?

**Comment by KKiiya** [comment]
> Amongus Done yet?
> 

what

**Comment by tomkeuper** [comment]
> Amongus Done yet?

Not yet haha I will test it more tommorow. It works just not how i want it

**Comment by tomkeuper** [comment]
I think it works fine, I just tested it and I thought it wasnt working as expected but it does. The current method duplicates the drop to the other person in the gen, this is the same as hypixel but if needed this can always be changed

**Review by Xxyuri2005xX — APPROVED** [review]

**Review by KKiiya — APPROVED** [review]

**Pull request merged**
