### PR TITLE
Added addon api for a better development (I will show an example on how to set it up)

### PR DESCRIPTION
**Pull request by KKiiya**

### CODE REVIEW

**Comment by Xxyuri2005xX** [comment]
I just ask if was wanted to delete all these files

**Comment by KKiiya** [comment]
> I just ask if was wanted to delete all these files

If im not wrong this is to delete them from the pull request (? 
Prob im wrong, im still pretty new at pull requests

**Comment by tomkeuper** [comment]
Yes something is not right here. You shouldnt delete all those files, you just had to choose a different branch to push to. are the changes that you made short?

**Comment by KKiiya** [comment]
Yes the changes are pretty short

**Comment by tomkeuper** [comment]
If you want I can help you with forking the right branch and also how to publish to the right branch

**Comment by KKiiya** [comment]
Yes i would like to, thanks

**Comment by Xxyuri2005xX** [comment]
If kiiya agrees, I would move his pull of the addon system to #165

**Comment by tomkeuper** [comment]
> If kiiya agrees, I would move his pull of the addon system to #165

To the api-ify branch you mean?

**Comment by Xxyuri2005xX** [comment]
> > If kiiya agrees, I would move his pull of the addon system to #165
> 
> To the api-ify branch you mean?

yes, I would move it to the api-ify branch being also an API improvement

**Comment by KKiiya** [comment]
Yeah i agree 100%, i dont have any problem

**Comment by tomkeuper** [comment]
> > > If kiiya agrees, I would move his pull of the addon system to #165
> > 
> > 
> > To the api-ify branch you mean?
> 
> yes, I would move it to the api-ify branch being also an API improvement

I already mentioned that in a DM, but this PR cannot be merged like this due to all the removals.

**Comment by Xxyuri2005xX** [comment]
meaning, we use the right classes by possibly doing a "copy-paste" into its own dedicated commit.
one example is with the PlayerMoneyGainEvent, I used kiiya's pull as a base after getting his consent and copying the code snippets

**Pull request closed without merging**
