### PR TITLE
make villagers silent

### PR DESCRIPTION
**Pull request by ImYenil**
Added villager mob slient in version 1.8.8

### CODE REVIEW

**Comment by tomkeuper** [comment]
you make me question if silent is spelled 'slient'

**Review by tomkeuper — APPROVED** [review]

**Comment by Xxyuri2005xX** [comment]
Is this modification already present in other versions?

**Comment by ImYenil** [comment]
> Is this modification already present in other versions?

Other versions already have Slient. Only version 1.8.8 doesn't have this feature

**Comment by tomkeuper** [comment]
Slient :(

**Comment by Xxyuri2005xX** [comment]
I checked and confirm, it is there in all but 1.8, thank you for your reply

**Review by Xxyuri2005xX — APPROVED** [review]

**Pull request merged**
