### PR TITLE
Fix the default config for Next Event Bed Destruction

### PR DESCRIPTION
**Pull request by AgentNoobff**

### CODE REVIEW

**Comment by AgentNoobff** [comment]
So that the scoreboard doesn't bug out like this 👇

**Comment by Xxyuri2005xX** [comment]
can you please do the same with other languages?

**Comment by AgentNoobff** [comment]
Screenshot_20230721-223623~2
So that the scoreboard doesn't bug out like this ^

**Comment by Xxyuri2005xX** [comment]
> can you please do the same with other languages?

if the text lenght is like the english one

**Comment by AgentNoobff** [comment]
> can you please do the same with other languages?

Hmm alr im kinda new to github, do I need to make separate PRs for all the languages?

**Comment by Xxyuri2005xX** [comment]
you don't need to do other pulls, just do a commit inside the same branch.
But the other languages look at the length first because some languages it's possible it's already ok

**Comment by AgentNoobff** [comment]
> you don't need to do other pulls, just do a commit inside the same branch. But the other languages look at the length first because some languages it's possible it's already ok

I checked, all of them have the same text, "Beds Destruction". I'll do it wait.

**Comment by AgentNoobff** [comment]
This was closed because I made a new PR with the necessary changes made.

**Pull request closed without merging**
