### PR TITLE
fixed inventory issue

### PR DESCRIPTION
**Pull request by ImYenil**
fixed https://github.com/tomkeuper/BedWars2023/issues/131

### CODE REVIEW

**Comment by tomkeuper** [comment]
There already is a inventory click event registerd. so I dont want to register it another time as it might conflict.

**Comment by ImYenil** [comment]
> There already is a inventory click event registerd. so I dont want to register it another time as it might conflict.

Then where did you put this code?

**Comment by tomkeuper** [comment]
idk if you are doing this on purpose but you already tried to pr this before #123

**Comment by ImYenil** [comment]
> idk if you are doing this on purpose but you already tried to pr this before #123

Did you see the video about this bug?

**Comment by tomkeuper** [comment]
> > idk if you are doing this on purpose but you already tried to pr this before #123
> 
> Did you see the video about this bug?

Did you see the comments in the other PR?

**Pull request closed without merging**
