### PR TITLE
Fix default tower item

### PR DESCRIPTION
**Pull request by ImYenil**
Fixed bug where wrong tower item was added as invalid material in shop.yml

### CODE REVIEW

**Comment by tomkeuper** [comment]
Please merge the open PR on your fork

**Comment by ImYenil** [comment]
> Please merge the open PR on your fork

I already did it on my fork?

**Comment by tomkeuper** [comment]
> > Please merge the open PR on your fork
> 
> I already did it on my fork?

Your branch is 1 commit behind. It could have been a different branch tho.

**Review by tomkeuper — APPROVED** [review]

**Comment by tomkeuper** [comment]
@porudev can you review and merge if approved?
Dont worry about the lore being added this will be fixed after

**Review by porudev — APPROVED** [review]

**Pull request merged**
