### PR TITLE
Ender dragon changed

### PR DESCRIPTION
**Pull request by ImYenil**
Ender dragon event no longer makes team generators location AIR when starting

### CODE REVIEW

**Comment by Xxyuri2005xX** [comment]
sounds intresting, but maybe implement also an option in config with false as default (if true it removes blocks and false keeps them), with the option would be possible to give customization to this event.
example of name: **sudden-death-generator-replace-block: true/false** or something similar

**Comment by tomkeuper** [comment]
I am quite sure i removed something like this before aswell. And because its weird behaviour I didnt add a config option either.
https://github.com/tomkeuper/BedWars1058/commit/785386b3ce7d19c67ae8d8d2944f7568c94fb512

**Comment by Xxyuri2005xX** [comment]
i can implement that option by myself and open the pull request if you want

**Comment by tomkeuper** [comment]
> i can implement that option by myself and open the pull request if you want

Could you re add the part I removed before? under the same config option?
And default false please :D

**Comment by Xxyuri2005xX** [comment]
i can do it now

**Comment by Xxyuri2005xX** [comment]
done, #44

**Comment by tomkeuper** [comment]
Closing in favour of #44

**Pull request closed without merging**
