### PR TITLE
Implement Footsteps on all versions

### PR DESCRIPTION
**Pull request by ImYenil**
Implement Footsteps on all versions

### CODE REVIEW

**Comment by KKiiya** [comment]
Can i ask why you used "EXPLOSION_NORMAL"?

**Comment by ImYenil** [comment]
> Can i ask why you used "EXPLOSION_NORMAL"?

Since the footstep particle no longer exists, I replaced it with this

**Comment by KKiiya** [comment]
Yes, the particle doesnt exist but we cant send explosions evertime someone gets invisible and walks. If this is temporary, its okay

**Comment by tomkeuper** [comment]
In my opnion it should be either footstep or something different completely (a particle that exists on all versions)

**Comment by ImYenil** [comment]
> Yes, the particle doesnt exist but we cant send explosions evertime someone gets invisible and walks. If this is temporary, its okay

It's temporary

**Comment by tomkeuper** [comment]
I dont think this is a good solution.

**Comment by ImYenil** [comment]
> I dont think this is a good solution.

So what would you like me to do? footstep particles don't exist anymore

**Comment by KKiiya** [comment]
> > I dont think this is a good solution.
> 
> So what would you like me to do? footstep particles don't exist anymore
> 

not adding explosions, just leave it empty

**Comment by ImYenil** [comment]
> > > I dont think this is a good solution.
> > 
> > 
> > So what would you like me to do? footstep particles don't exist anymore
> 
> not adding explosions, just leave it empty

I'll add a configuration to change this

**Comment by ImYenil** [comment]
> > > I dont think this is a good solution.
> > 
> > 
> > So what would you like me to do? footstep particles don't exist anymore
> 
> not adding explosions, just leave it empty

Implement

**Comment by KKiiya** [comment]
I dont think this is a good solution

**Comment by ImYenil** [comment]
> I dont think this is a good solution

So what solution do you need?

**Comment by KKiiya** [comment]
For now just leave the version support above 1.12.2 empty (the playFootStepParticle()), we are trying to add footsteps, not particles by choice, we need to search about this deeper

**Comment by tomkeuper** [comment]
Agreed unless there is an actual replacement or workaround to get the footstep particle I think we should leave it empty for now

**Pull request closed without merging**
