### PR TITLE
Fix player list in Teleport GUI parsing wrong target

### LINKED ISSUE #148: Teleport GUI target wrong person when parsing placeholders
What the title said

### PR DESCRIPTION
**Pull request by porudev**
Fix player list parse the wrong target

image

Fixes #148

### CODE REVIEW

**Review by tomkeuper — APPROVED** [review]

**Comment by KKiiya** [comment]
I dont understand this bug, where was the problem at?

**Comment by tomkeuper** [comment]
> I dont understand this bug, where was the problem at?

I believe its because VenNux is not the owner but poru (who opened the menu) does have the owner prefix

**Comment by tomkeuper** [comment]
@porudev can you confirm?

**Review by Xxyuri2005xX — APPROVED** [review]

**Comment by porudev** [comment]
> 

I confirm!

**Pull request merged**
