### PR TITLE
Fixed https://github.com/tomkeuper/BedWars2023/issues/119

### PR DESCRIPTION
**Pull request by ImYenil**
Fixed https://github.com/tomkeuper/BedWars2023/issues/119

### CODE REVIEW

**Comment by tomkeuper** [comment]
How does this work?

**Comment by ImYenil** [comment]
> How does this work?

It was developed to prevent clicking the default item or tool from the chest inventory or enderchest inventory.

**Comment by tomkeuper** [comment]
Wouldnt it be better to cancel the item drop event? So players can still move the default item around

**Comment by ImYenil** [comment]
> Wouldnt it be better to cancel the item drop event? So players can still move the default item around

The code written by andrei1058 didn't completely block it. So I replaced it with InventoryClickEvent and it fixed perfectly

**Comment by tomkeuper** [comment]
closing due to being fixed with a better solution

**Pull request closed without merging**
