### PR TITLE
Added new messages and add sounds

### PR DESCRIPTION
**Pull request by ImYenil**
added new messages and sounds

I only work in English. other languages ​​manual

### CODE REVIEW

**Comment by Xxyuri2005xX** [comment]
implements the messages in the other languages as well which is better. Even just in English but put them.

**Comment by ImYenil** [comment]
> implements the messages in the other languages as well which is better. Even just in English but put them.

I don't know any other language.

**Comment by tomkeuper** [comment]
> > implements the messages in the other languages as well which is better. Even just in English but put them.
> 
> I don't know any other language.

Thats why he said you can put it in english aswell. Not putting anything will cause errors

**Comment by ImYenil** [comment]
> > > implements the messages in the other languages as well which is better. Even just in English but put them.
> > 
> > 
> > I don't know any other language.
> 
> Thats why he said you can put it in english aswell. Not putting anything will cause errors

Work progress has been completed in other languages ​​as well

**Review by tomkeuper — APPROVED** [review]

**Pull request merged**
