### PR TITLE
Add invisibility footsteps

### PR DESCRIPTION
**Pull request by ImYenil**
Add invisibility footsteps

### CODE REVIEW

**Comment by KKiiya** [comment]
Works in 1.8 and 1.12,.
This needs to be tested in other versions to prevent errors since its deprecated (1.16.5, 1.17.1, 1.18.2, 1.19.3)

**Comment by tomkeuper** [comment]
@ImYenil since you own the repo can you resolve the conflict?

**Comment by ImYenil** [comment]
> @ImYenil since you own the repo can you resolve the conflict?

I can't solve this by clicking on it.
image

**Comment by tomkeuper** [comment]
Yes because you are using an outdated branch

**Pull request closed without merging**
